### ISSUE TITLE
How to implement the capsule?

### ISSUE THREAD

**Issue by Rikaius** [maximeq/three-js-capsule-geometry#1]
I'm new to Javascript.

I found your code and I do not know how to implement it in my project.

You could write a sample code on how to implement the capsule.

Thank you!

**Comment by maximeq** [comment]
Hi !
Will see if I can add an example, but actually it's pretty straightforward as it works like any three.js geometry class (if you are new to three.js, you should play with ti first).

You can include one of the dist/browser/ files in your webpage (THREE must be included first), then THREE.CapsuleBufferGeometry will be defined and possible to use.

As for parameters, they are similar to other *BufferGeometry classes in three.js.

**Comment by maximeq** [comment]
I added an example, along with a bug fix reported today. 
Should be easier to play with it now.
