### ISSUE TITLE
Help need

### ISSUE THREAD

**Issue by maxmeli123** [maximeq/three-js-capsule-geometry#4]
Hi, many thanks for posting this library,
sorry this is not an issue but just I need some help using this library. I wrote here because I do not know how contact you. 
I'm new to JS and threejs, just use it from one week, I do not know what is npm, I just import three.js on my project (inside an HTML as plain text), even imported orbitcontrols.js and all works well.
Because I need to simulate a 3D printer filament I need a cylinder with round cups and I've two options, or use a cylinder with two spheres or use a capsule object. Because I load big files with a lot of filament segments (from 50.000 to 1.000.000) I think this class is what I need (if Android device RAM permits it) but I do not know if I can just import it as JS file like others I already imported. I read it has some external dependences and not sure how I can use it.
I've another option, the threejs documentation has a CapsuleGeometry too, but using threejs 138 it do not contain the class, I've searched it with a text editor and nothing found.
Please can you help me figure how to make it work?
Please feel free to move this discussion in the right place and sorry another time.
Many thanks

**Comment by maximeq** [comment]
Hello,
If you need the 2 spheres to have the same radius, Three.js CapsuleGeometry should do the job, it's included in the core src folder under geometries.

Otherwise I must admit I did not update this folder to depend on the last three revision. It's probably not much to do though.
Easiest way for you is to just copy the source I believe, if you use it as a package or just use the dist files, it will not depend on the proper three revision and may break.

**Comment by maximeq** [comment]
I'm not sure it will run smooth with 50k to 1000k objects. At least you will need to merge that into a single object. 
Depending on your specific usecase, you could also use a raytracing shader to limit the number of polygons, and reach per pixel accuracy, like in https://capsulesketch.org/, but this one is a proprietary shader.
May not work on some older mobile though.

**Comment by maxmeli123** [comment]
Hi maximeq,

many thanks for your replies and suggestions.

Yes I only need  2 spheres to have the same radius, it simulate the plastic filament extruded by nozzle of a static size, by default it is 0.4 mm, but can be changed to 0.2. 0.3. 0.5, 0.6, 0.8, 1.0 mm.

Now I updated my theejs 138 to latest 139, the CapsuleGeometry do not exists on 138, it was added in 139. 

I've tried it and worked well, I've tried to simulate an extrusion and looks good as I expected, so I created one capsule geometry with 0.4 mm diameter, using a for loop I've created more than one to simulate a piece extrusion, here I see that depending on resolution I set for a capsule and radials threejs slow down with just a couple of these (50-100). I'm not sure if it is possible.

This on Android devices, in past I had the same problem on desktop devices (PC and Raspberry) using Java3D, I need to balance the resolution not too high, eg. 8 segments for radials and 8 for cups and search to optimize it.

Note that I only use one geometry (and material)  instance for all segments this way:
<code>
//// FILAMENT TEST ////
const filamentSize = 0.4;
const radius = filamenSize / 2;

const capGeo = new THREE.CapsuleGeometry(radius, 10, 8, 8);
const capMat = new THREE.MeshPhongMaterial({color: 0x00FF1F});

var x = 0.0;
var y = radius;
for (let pY = 0; pY < 3; pY++) { 
	for (let pX = 0; pX < 30; pX++) {
	   capsule = new THREE.Mesh(capGeo, capMat);
	   capsule.rotation.x = THREE.Math.degToRad(90);
	   capsule.position.x = x;
	   capsule.position.y = y;
	   capsule.position.z = -15.0;
	   //capsule.position.set(x, radius, -10.0); 
	   scene.add(capsule);
	   x += filamentSize;
	}
	x = 0.0;
	y += filamentSize;
}
</code>

I've attached a screenshot so you can see what I do.

Because I'm very new on JS and even on threejs (I use it from 2 weeks) I have another question not related to a capsule if possible.... 

In my project I recreate the threejs HTML template, import on it a three.js and orbitbehaviors.js as plain text, then insert in the <script> tag all my JS at runtime, this works very well, but now I want to add Stats to show a framerate and a GUI to insert controls like sliders to iteract with the scene in realtime, but it won't work.

I've imported Stats.js the same way and my JS code is this:
<code>
// See: https://github.com/mrdoob/stats.js
var stats = new Stats();  // 0: fps, 1: ms, 2: mb, 3+: custom
stats.showPanel(0);
document.body.appendChild(stats.dom);
</code>
and then in the function animate() i put this:
<code>
stats.update();     // Needed to update stats

// ... or
   // stats.begin();
   // ... monitored code goes here ...
   // stats.end();
</code>
but it won't work.

For GUI I do not found a way, I've downloaded all threejs bundle but I do not find it, then I imported and used this way but even it won't work:
<code>
import { GUI } from 'https://threejs.org/examples/jsm/libs/dat.gui.module.js';
// then used this way ...
var gui = new dat.GUI();
gui.add(group.scale, "x", 0.1, 5);
gui.add(group.scale, "y", 0.1, 5);
gui.add(group.scale, "z", 0.1, 5);
</code>

Many thanks

**Comment by maxmeli123** [comment]
Sorry, I forgotten screenshots ..... I don't like much cups...
![20220402_115050](https://user-images.githubusercontent.com/31792553/161378726-ce11b44c-c476-407f-af79-cff201da407b.jpg)
![20220402_115306](https://user-images.githubusercontent.com/31792553/161378736-4c1a660c-23fb-4575-b50f-9b2b7324c935.jpg)
![20220402_120201](https://user-images.githubusercontent.com/31792553/161378743-0ed9b3f6-927b-4aa2-91a5-dff35e236289.jpg)

**Comment by maxmeli123** [comment]
I am not completely satisfied of this, mainly by the cups that have a strange orange wedge shape .... I would like to try your class, so how to import it? I copy a class inside three geometries, and then?

**Comment by maximeq** [comment]
I can't help you concerning the UI issues. 

To use the class in this repository, you just need to import the file and then do
`new CapsuleBufferGeometry(...);`

However, I'm not sure it works with Three revision 139, some the code may need to be adapted. May find time one of those weeks.

Your subdivision choice is not consistent, if you want the extremities to look like the tube you need less subdivisions on the heads and more on the chunk.
Here for example, if you select smooth shading with 12 radial segments and 6 top and bottom segments you have something pretty nice:
https://dualbox.com/apps/capsule-geometry/production

Also something is wrong in your shading, I don't know if the Three js capsule class is not providing the normals but your code should lead to smooth shading and it does not.

Concerning performances, as long as those objects don't move independently from each other, you should not create 30*3 = 90 Meshes as you do. 
You should create a new geometry, apply transformations to the geometries (see BufferGeometry class it has the required methods), then use https://threejs.org/docs/#examples/en/utils/BufferGeometryUtils to merge all geometries and only have 1 mesh.
With subdivisions leading to around 200 triangles per objects you should be able to reach 1000 static capsules with acceptable performances I believe. At least on devices < 2 years old. 

Will see if I can find  a couple of hours to update this repository for last three.js version.

**Comment by maximeq** [comment]
Do you have a jsFiddle or something you can share where I could edit the code ?

I'm curious about the context of your project, is it a professional software you are writing ? 
I believe simulating filaments with 1 million capsules can be quite a challenge in terms of performances, especially if the scene is dynamic.

**Comment by maxmeli123** [comment]
Hi maximeq, I think Max like me right?

I'm very, very, very Happy you are curious of my things, I really apprecciate it...

Because you are curious, I not sure if this is a right place, but because you asked me I want to explain better my situation.

Yes this is a really big project I started some age agos and I worked on it 12-15 hours every day. When this app is finisched I want to sell it on Google Play Store and start it as my work to develop other apps... For now it do not produced nothing in $ terms, need to be finished, then released, I'm at good point but need more time, I think about one year.

In 2018 I started to write an app (Desktop) capable to read gcode files (sliced and produced by slicing software like slic3r, Prusa Slicer, Cura, Simplify3D etc...) for a 3D printer, simulate it on a Canvas 2D where I draw it with simple lines by changing a line width attribute as  plastic extruder filament size, draw a grid (with centimeters and millimeters) that is the 3D printer plane rappresentation. This grid can be set from Settings because not all printers have the printing plane the same dimensions. 

This app do not only simulate the 3D printing process by drawing it, but by connecting the 3D printer to a PC (or Raspberry PI) over USB can control it manually (with sliders and buttons), load gcode files, draw these on a canvas line by line and send to a 3D printer that print the object.

Initially I started with a canvas that see the 3D printer on top view, so the printing plane just as a square or rectangle or circle for some particular printers (Delta). The next step was that I created a static 3D view on a 2D canvas by adding some math calculations to my viewer class. The final results is that the 3D printing plane is rotated 45 degrees (no perspective, ortographyc view), looks like a rombe.

It looks good I really like my work, but there are a lots of limitations, It can be zoomed in-out, but every time it clear a full canvas , do calculations and redraw the grid. If there are printed object on the plane it clear all.
For Pan I can do it because I've put a big canvas, like 3000x3000 pixels inside a 2D scrollview, this permit to zoom and pan the plane.

After this I worked with Java3D, that is even a cool and powerfull library like ThreeJS, both are very similars, I've created an app version with a full 3D view, I'm impressed of what I can do with it, all works apart that after 500-1000 segments drawed the app crashes with the Java Exception HeapFull, this even probalbly because I'm on a very old system with Win XP 32 bit on a Dualcore PC with 2GB of ram. Maybe on 64 bits PC quadcore or octacore it works well, even Java on 32 bits allocate max 2GB for a virtual machine, on 64 bits if I remember 4 or 8 GB.

Here for now I not have updated my desktop app and passed directly to Android that is my goal, so all next features I explain now are only on Android app.

As I said, next step was to port all this work to Android (I'm an Android and Desktop developer, even I manage electronics programmed with Arduino IDE in C++). 

After I ported it (not really simple) I was able to simulate printer directly to my smartphone, then connect it with OTG USB Cable to a 3D printer, control it manually, load gcode files, print it with a printer. The app read line by line a gcode file (I even loaded files of 20-30 MB on my Google Nexus 7 SE that have more RAM that my phone, for a total of 1.600.000 gcode lines), extract all coordinates (line by line) send to a 3D printer and draw it. So One by One, not once. In simulation there is a slider to set the simulation speed.

The next step was to control a 3D printer remotely via WiFi in local and over Internet, control manually and via gcode, even place an IP Camera (I use ESP32CAM [https://www.amazon.com/DEVMO-ESP32-CAM-Bluetooth-Development-OV2640/dp/B07S4DRLYM/ref=mp_s_a_1_1_sspa?keywords=esp32+cam&qid=1648940779&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzTTdYQjUwSDlCM0ZZJmVuY3J5cHRlZElkPUEwMDExNzYyV1BGM1NQQ1FSM1BGJmVuY3J5cHRlZEFkSWQ9QTAxNjg0MDUyUEI5MkRTSzI5V0FLJndpZGdldE5hbWU9c3BfcGhvbmVfc2VhcmNoX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=](url)
 or Raspberry + Cam). My app has a dedicated page to view the IP Camera streaming in MJPEG format.

Because I always search the best, and my initial idea was to expand it, now this app do not only do what I explained, but i extended it to work with CNC machines and Laser cutting machines, next days I wont to add a Foam cutter machines.
Each one of this have it's Layout that can be selected from Settings, so if eg. one use it just for laser do no see things related to a 3D printer or other machines. But the interface (apart some small needed changes) is the same, control a 3D printer result the same as use a CNC to engrave a piece of wood, metal etc... or engrave with laser a 2D realistic photo on a piece of wood or cut a piece of cardboard.
The laser is what I do not have to test with, but it is really cool (and dangerous for eyes, need dedicate eyeglasses) it can cut as fine as an hat, generally the laser point is around 0.05 mm if right focused, it can cut materials, or engrave images on materials (much but not trasparents like plexiglas and no metal, only can engrave on anodyzed aluminium). You can see videos on Youtube on this. 
My app can read gcode files produced with LaserGRBL and similars, simulate realistic photo engraving and laser cut it can control (no yet tested) a real laser machine via USB, WiFi and Internet.

The app even have the ability to do timelapses, so I've programmed ESP32CAM or Raspberry + Cam to take photos, save to microsd as backup, send over wifi (with its name) in local or over Internet to my app that show it, save it and when the piece is finished have a dedicated page where read all images, do a lots of options like framerate, size, codec etc... use FFMPEG co create an MP4 video timelapse.

All these machine are a bit differents, but conceptual the same, there are axis, motors that move it, an electronic controller with a firmware, generally GRBL or Marlin that looks as serial controller and gcode interpreter, so if I send a command G1 X123.000 Y32.456 Z132.454 (G1 is a movement command) the controller interpret it and do the exact movement with stepper motors that have an high resolution 32 - 64 -128 -256 microsteps.

All machines are a bit differents, each axis have a motor eg:
- 3D printers has XYZ axis, then E that is the plastic filament extruder, 
- CNC machines generally have XYZ axis, more professionals have ither 2 rotating axes, A and B or C
- Lasers are like a plotter, only cartesian XY axis
- Foam cutters too, have 2 XY axis and and HOT filament that is just on-off

So at the end my app when finisched can simulate, manual control, load gcode and work it on a 3D printer, CNC machine, Laser cutter machine and Foam cutter machine, all in one single app. I even evalutated to sell it in bundle and even create an app for any machine type.

After this long explanation I hope you can know better what I'm doing around this. :D

Returning to our discussion, I've tried your Dualbox with 12 radial segments and 6 top and bottom segments, and yes, it looks better, I will try to change it in my tests and final production.
For your class I need to test if works with 139 and yes many thanks if you have time to updare it, this is great, I'm sure that other users always want it updated because it has something thar threejs CapsuleGeometry do not have, the possibility to set both cup radius  indipendently, not needed in my case but really useful option.

You asked me: Do you have a jsFiddle or something you can share where I could edit the code ?
I develop on a pretty old pc with Windows XP 32 bits 2 GB RAM DualCore,  my browser (Firefox) open the jsFidle or Dualbox page), but because it  is a really old release I cannot see nothing on the canvas. Some time I tested with a web page that test browsers capability, it told me that support WebGL, even WebGL2 but no it not show nothing, sometime a white canvas, sometime just black. With my tablet and phone some demos works, others no.

For this reasons, because I'm a developer, I created a simple app with 3 tabs. 
- on first tab there is a long scrollable text (not colored syntax for now but I still search to implement CodeMirror code editor) where write just the JS code, no debug no all, if user just miss a semicolon or import something wrong or do wrong syntax no preview is rendered
- when user hit tab 2 there is a WebView that load a threejs HTML template, import three.js and orbitbehavoir.js (from internal asset memory) and add as plain text inside a <script> tag, even the app add the javascript the user write, so construct a full HTML string and pass to the browser that load all locally and render the threejs scene.
- in the third tab , not yet implemented I want to write a full HTML as plain text, then put a small button to copy it to the clipboard so cam be pasted on jsFiddle, then add two more buttons, one to save HTML file and other to load saved, try to extract JS code and put it in the first tab.

If you want to try my apps I can send you yes, so you can see yourself, I can send directly apk files to be installed, need Android, iOS not supported, one is my app to print etc... but it just start in simulation, no machine needed, as render a 3D static view or a 2D, can be set on Settings (require app restart) and with other app with tabs by default it make a JS code I wtote as string, so just need to press on TAB2 and it render the scene, then the JS code can be changed... is a bit trikly but works, next I see if I can implement CodeMirror editor and Eruda console, not sure for this....
Then I can send you a Java3D desktop app, but you need to install Java3D (I do not know if you know it and already used) that is just a small Java extension about 5MB, after this all Java3D works.... 
Even on Rarpberry or linux works, I've a Raspberry with touchscreen and the app works touch, already adapted to be fullscreen, the same file .jar works on win, linux, Mac (not tested)

If you interested to see these, please do some time and I will post the link where you can downoad.

At this point I'm curious to know what you think on this, if tou read all my big message many thanks, so I'm sure you interested on what I wrote.

Many thanks

**Comment by maxmeli123** [comment]
Sorry maximeq, 

I wrote this to try to explain to you what I do and why I thought you might be interested in dealing with the 3D world, unfortunately it is a bit complex to explain, even to me, even that englisf is not my language.... Fortunately you ar not Chinese :D .... so required a long explanation.

Since I do not want to cause you problems, if my message is too long I delete it.
Many thanks

**Comment by maximeq** [comment]
Hello,
No problem you are not bothering anyone I guess.
I'm just running out of time and can't answer right away but I will eventually :)

**Comment by maxmeli123** [comment]
Thanks max !

**Comment by maxmeli123** [comment]
Hi max, you asked me:

Do you have a jsFiddle or something you can share where I could edit the code ?

Yes I have it, with my app I wrote to test THREEJS there is a inline Javascript code and a WebView to render a scene. The app do not have capability to Load/Save, but as default I've put the Javascript functions where iI can iteract with B4A to call JS stantments and functions, even viceversa, JS send to B4A. So I still searched to recreate functions to draw a filament to integrate in my 3D printing app.

Now I'm here that I cannot know how to put more segments one after other using a pivot rotation, translate or something else. I've the same function working for Java3D but I do not know how to convert to rhreejs to put all capsules one after other.

Sorry this is not my hobby, this is my work, if I do not find a solution in some days I will abandone it and mantain original 2D view. I can send you my Android app to test my code. Please help.

**Comment by maxmeli123** [comment]
Hi,
please, what is the problem you cannot reply to me and help about your CapsuleGeometry I want to use ?

I don't want you make my app, I just searched for a CapsuleGeometry for threejs, I found your that seem good.
I use latest threejs 139, tried to import it but there are errors, so temporary I've used the internal CapsuleGeometry waiting that you provide an update so me and other users can use it on latest treejs.

I do not need to create games or some complex things, for my app I just need to recreate the 3D printer plane and plastic filamet (capsule), the first already is done, for filamet I just need a CapsuleGeometry placed one consecutive to other... Only this...No other.

I asked you for some advices because I'm new to threejs, and write long explanation just to explain you what I need to do with a capsule geometry, just for this, I even wrote 'If you not interested, just skip read and just read the relevant part relative to CapsuleGeometry' .
 The work I need to do is not a complex thing, just what I wrote, so use your CapsuleGeometry, place it in tight position and rotate to make it one consecutive to other. STOP no other.

Is that possible? Is this more complex to you? 

Thanks

**Comment by maximeq** [comment]
The main problem is that I have a job, a company to run and a personnal life :)

As soon as I find time to update to last version of Three.js, I will do. But since Three.js made one, I need to make sure that mine will be compatible and compliant with the API of the one in Three.js.

I read your explanation, now if you had a direct link to a simple web page where I can check, it would have been simple to quickly read the code and give some advice (that's why I asked for a jsfiddle or similar). But if it's not that simple to access honnestly I won't have time.

In theory using the three.js class should be enough as long as you don't need to have varying radii. If you can't make it with the Three.js class, not sure you can with this one (the only additional feature is that my class handles having a capsule with 2 different radii).

Now if it is that important to you, and if you need professional expert assistance, I can find people to help you but it will not be free... :/

Otherwise I will let you know as soon as I can update this lib, but can't commit to any specific delay.

**Comment by maximeq** [comment]
Hello,
The lib has been updated to rev 138. We cannot easily update to 139 as it collides with the new Three.Js version.
There is an example so you should be able to use it on your own.

**Comment by maxmeli123** [comment]
Hello,

Good, but I still used 139 here because it the only that contain CapsuleGeometry,
but not a problem, i can downgrade, but not simple switch 139 to 138 to test both because I import as static file. 

Do you have an Android device ?

I've developed a simple app just to test threejs, there is a page where print javascript and a page with a webview where you can see the result rendering, no dependency required, ot already include three.js, orbitcontrol.js, stats.js, gui.dat.js and some loaders. I still test on it, I've added some threejs code examples, even my tests with 3D printing filaments.

It only works on Android, no iOS, no PC. I send you?
Can you provide an email or I post a download link?

If you do not have Android device I can provide the Javascript file you can copy/paste on a jsFiddle or a threejs HTML template, this way you need to import yourself three.js, orbitcontrols.js and stats.js.

Many thanks

**Comment by maxmeli123** [comment]
Possibly using it directly on Android device, smartphone or tablet is the best approach so we can even test performances.
Many thanks

**Comment by maxmeli123** [comment]
So this is a situation....

I'm not a profit company, is not clear to me what you thinked about it, Im just a private person that had no work and cannot find it, I still searched to write this 3D printing app to sell it as my work, I worked on it last five years.

Because I have no work I cannot paid for help, I've no money for it, for this reason I asked you to help me, just I need one hour of your time, but seem that this is possible only if I paid it and this is not possible as explained.

What I can do is just send you FOR FREE my app I wrote to test THREJS. This app is not Super, I wrote it in just  a month, but it permits to test threejs scenes on mobile devices in local, no internet required, no other files required (like javascripts) no dependences required, just launch the app, load some test JS files or write your, press a button and see the scene rendered.

Please understand me, I do not know what else to tell you, for my part I have put all my effort into it, even if I do not know well threejs are I have already managed to render my plastic filament, even whole blocks via code, but I need your advice because I can't go on and I don't know if what I did I did it in the right way or it can be done better.

Please help me, if you cannot help me i will have a very big problem, I have no more time to spend to it, this is just a small part of my 3D printing app, it is a complex app capable to control machines over internet, see these via IP cam and more.

Thanks

**Comment by maxmeli123** [comment]
If you can't do it for me, do it to help technological development, my 3D printing app can do things that are still impossible to do otherwise and no other app in its context is capable of doing. When I release my app I am sure there will be engineers who will try to emulate what I did, for me this is fine as it helps the technological development process, also I will have a window of time before I find my developed ideas on the market ( and probably improved) by others, it will take some  time before they can do it.

**Comment by maximeq** [comment]
I'm also quite limited in terms of availability, that's why I was proposing to help with other ressources, which are not free unfortunately.

Can you give me access to a private repository on github with the javascript code in sucha way that I just have to pull & launch to test it?
I will need the code you want me to look at to be the actual source code without obfuscation. The rest of the code can be ofuscated if you don't want to risk your IP.

We will continue the conversation on your repo since your questions are much broader than just asking how to use this library.

**Comment by maxmeli123** [comment]
My JS code is not on github, if you provide me an email I will send you, or the easier way is to install my small android app, it contain my last JS code, I've already experimented a render extrusion with CylinderGeometry + endcip SphereGeometry (obtaining a very good result) and the same with ThreeJs CapsuleGeometry, I do not tried your CapsuleGeometry because I need to change my code with static imports, so need to try it importing three.js 138.

In both cases after a couple of segments I have a very low framerate, like 10 fps, note that any segment
is added with new keyword, same for material and mesh....

Because is not to simple continue the conversation on my github, I've other projects on it but only opensources projects, do you have a Facebook Messenger account? This way we can chat and I can send you code, screenshots, even small videos if needed. And we are realtime... If you do not have more time, please contact me when you have some time.

This is my profile,  so I can send you the last my JS code and/or my WebGLBrowser app that contain my code and can render it, even it now show a full HTML.

https://www.facebook.com/meli.massimo.3/

**Comment by maximeq** [comment]
OK Let's continue the conversation elswhere.
I'm closing the issue.
